---
title: "spillR-vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{spillR-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse=TRUE,
    comment="#>"
    )
```

```{r setup, warning=FALSE}
library(spillR)
library(CATALYST)
library(dplyr)
library(cowplot)
bc_key <- c(139, 141:156, 158:176)
sce_bead <- prepData(ss_exp)
sce_bead <- assignPrelim(sce_bead, bc_key, verbose = FALSE)
sce_bead <- applyCutoffs(estCutoffs(sce_bead))
sce_bead <- computeSpillmat(sce_bead)

# --------- experiment with real cells ---------
data(mp_cells, package = "CATALYST")
sce <- prepData(mp_cells)

# --------- table for mapping markers and barcode ---------
marker_to_barc <- 
    rowData(sce_bead)[,c("channel_name", "is_bc")] %>%
    as_tibble %>%
    dplyr::filter(is_bc == TRUE) %>%
    mutate(barcode=bc_key) %>%
    select(marker=channel_name, barcode)

# --------- call compensate from compCytof package ---------
sce_spillr <- 
    spillR::compCytof(sce, sce_bead, marker_to_barc, overwrite=FALSE)

# --------- 2d histogram from spillR (for vignette, not for paper) -------
as <- c("counts", "exprs", "compcounts", "compexprs")
chs <- c( "Yb171Di", "Yb173Di")
ps <- lapply(as, function(a) 
    plotScatter(sce_spillr, chs, assay=a))
plot_grid(plotlist = ps, nrow=2)
# --------- plot with spillR ---------
spillR::plotDiagnostics(sce_spillr, "Yb173Di")

```
# Session Info {.unnumbered}

```{r session_info}
sessionInfo()
```
