extract_data <- function()
{
  set.seed(10^5)
library(CATALYST)
library(cowplot)
library(flowCore)
library(ggplot2)
library(SingleCellExperiment)
library(tidygraph)
library(ggraph)
library(tibble)
library(dplyr)
library(tidyr)
library(future.apply)
plan(multisession, workers = 8)
library(extraDistr)
library(RColorBrewer)
library(magrittr)
library(nnls)
library(flexmix)
library(countreg)
library(stringr)
  data(mp_cells, package = "CATALYST")
  sce <- prepData(mp_cells)
  channel_names <- as.matrix(rowData(sce))[,"channel_name"]
  counts <- t(assay(sce, "counts"))
  counts <- floor(counts)
  colnames(counts) <- channel_names
  counts
}
